apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain
  labels:
    app: brain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain
  template:
    metadata:
      labels:
        app: brain
    spec:
      containers:
      - name: brain
        image: k8s.azof.fr/azoff/brain:1.1.4
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: google-auth-json
            mountPath: /app/google-auth.json
            subPath: google-auth.json
      imagePullSecrets:
      - name: dockerconfigjson
      volumes:
      - name: google-auth-json
        secret:
          secretName: brain
          items:
          - key: google-auth-json
            path: google-auth.json
