apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain
  labels:
    app: brain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain
  template:
    metadata:
      labels:
        app: brain
    spec:
      containers:
      - name: brain
        image: k8s.azof.fr:5443/azoff/brain:1.0.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: brain
spec:
  selector:
    app: brain
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000