version: '3.3'

volumes:
  node_modules: {}

services:

  server:
    image: node:alpine
    working_dir: /server
    volumes:
      - ./src:/server/src:ro
      - ./static:/server/static:ro
      - ./google-auth.json:/server/google-auth.json:ro
      - ./package.json:/server/package.json:ro
      - ./package-lock.json:/server/package-lock.json:ro
      - node_modules:/server/node_modules
    ports:
      - "3000:3000"
    command: npm start
